// <auto-generated />
using System;
using CryptoWatcher.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoWatcher.Data.Migrations
{
    [DbContext(typeof(CryptoWatcherDbContext))]
    partial class CryptoWatcherDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptoWatcher.Entities.LiquidityPoolPosition", b =>
                {
                    b.Property<decimal>("PositionId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("NetworkName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInRange")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Token0Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Token0PriceInUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("Token0Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Token1Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Token1PriceInUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("Token1Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("PositionId", "NetworkName");

                    b.HasIndex("NetworkName");

                    b.HasIndex("WalletAddress");

                    b.ToTable("LiquidityPoolPositions");
                });

            modelBuilder.Entity("CryptoWatcher.Entities.LiquidityPoolPositionSnapshot", b =>
                {
                    b.Property<string>("NetworkName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("LiquidityPoolPositionId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<bool>("IsInRange")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Token0Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Token0FeesUnclaimed")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Token0PriceInUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("Token0Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Token1Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Token1FeesUnclaimed")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Token1PriceInUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("Token1Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NetworkName", "LiquidityPoolPositionId", "Day");

                    b.HasIndex("LiquidityPoolPositionId", "NetworkName");

                    b.ToTable("LiquidityPoolPositionSnapshots");
                });

            modelBuilder.Entity("CryptoWatcher.Entities.Network", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MultiCallAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NftManagerAddress")
                        .IsRequired()
                        .HasMaxLength(266)
                        .HasColumnType("character varying(266)");

                    b.Property<string>("PoolFactoryAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RpcUrl")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Name");

                    b.ToTable("Networks");
                });

            modelBuilder.Entity("CryptoWatcher.Entities.Wallet", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Address");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("CryptoWatcher.Entities.LiquidityPoolPosition", b =>
                {
                    b.HasOne("CryptoWatcher.Entities.Network", "Network")
                        .WithMany("LiquidityPoolPositions")
                        .HasForeignKey("NetworkName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoWatcher.Entities.Wallet", "Wallet")
                        .WithMany("LiquidityPoolPositions")
                        .HasForeignKey("WalletAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Network");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CryptoWatcher.Entities.LiquidityPoolPositionSnapshot", b =>
                {
                    b.HasOne("CryptoWatcher.Entities.LiquidityPoolPosition", "LiquidityPoolPosition")
                        .WithMany("PositionSnapshots")
                        .HasForeignKey("LiquidityPoolPositionId", "NetworkName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LiquidityPoolPosition");
                });

            modelBuilder.Entity("CryptoWatcher.Entities.LiquidityPoolPosition", b =>
                {
                    b.Navigation("PositionSnapshots");
                });

            modelBuilder.Entity("CryptoWatcher.Entities.Network", b =>
                {
                    b.Navigation("LiquidityPoolPositions");
                });

            modelBuilder.Entity("CryptoWatcher.Entities.Wallet", b =>
                {
                    b.Navigation("LiquidityPoolPositions");
                });
#pragma warning restore 612, 618
        }
    }
}
